docs_update_pl_header
Lightning-AI/lightning_sphinx_theme pull request #55
Opened 2022-09-23 18:25 UTC by Felonious-Spellfire

2022-09-26 11:14 UTC, awaelchli approved these changes

2022-09-27 12:29 UTC, yurijmikhalevich requested changes
Looks good with one nit. We shouldn't merge this until we've updated our header to function on non-lightning.ai domains. I am going to work on this now.

2022-09-27 12:29 UTC, yurijmikhalevich commented on js/inject-lai-webapp.js
> +  fetch("/injectwebapp")
Since this will be used on a domain other than lightning.ai, we should hardcode it here.

```suggestion
  fetch("https://lightning.ai/injectwebapp")
```

2022-10-05 13:05 UTC, yurijmikhalevich commented
Closing in favor of #57.

2022-10-05 13:05 UTC, closed without merging